services:
  proxy:
    image: nginx:1.22
    volumes:
      - type: bind
        source: ./gw/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: false
    ports:
      - 80:80