services:
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - type: bind
      #   source: ./nginx.conf
      #   target: /etc/nginx/conf.d/default.conf
      #   read_only: true
    ports:
      - 80:80